### ISSUE TITLE
Breakage when adding a duplicate credential

### ISSUE THREAD

**Issue by cnweaver** [scimma/hop-client#153]
Attemtping to add a duplicate credential currently fails with:

	Traceback (most recent call last):
	  File ".../hop_client-0.4.1.dev7+g7dfee7e.d20210831-py3.7.egg/hop/__main__.py", line 93, in main
	    args.func(args)
	  File ".../hop_client-0.4.1.dev7+g7dfee7e.d20210831-py3.7.egg/hop/auth.py", line 554, in _main
	    add_credential(args)
	  File ".../hop_client-0.4.1.dev7+g7dfee7e.d20210831-py3.7.egg/hop/auth.py", line 428, in add_credential
	    if args.force:
	AttributeError: 'Namespace' object has no attribute 'force'

That code should both check for the presence of the `force` property before trying to use it, and the calling code should actually implement the `--force` option to set it.

**Comment by myNameIsPatrick** [comment]
What did happen to `--force`? I thought this was part of `hop configure` when that was used to set up authentication before the CLI was changed.

**Comment by cnweaver** [comment]
It was probably just a mistake (on my part) that it got omitted from the CLI restructuring? Putting it in is very simlpe, luckily.
